[kg_paths]
aiml_kg = "~/neuromorphic-citation-network/data/kg/kg_aiml"
neuroscience_kg = "~/neuromorphic-citation-network/data/kg/kg_neuroscience"
neuromorphic_kg = "~/neuromorphic-citation-network/data/kg/kg_neuromorphic"

[metadata_paths]
aiml_metadata = "~/neuromorphic-citation-network/data/aiml/aiml_nodes.csv"
neuroscience_metadata = "~/neuromorphic-citation-network/data/neuroscience/neuroscience_nodes_updated.csv"
neuromorphic_metadata = "~/neuromorphic-citation-network/data/neuromorphic/neuromorphic_nodes.csv"
